const express = require('express');
const authMiddleware = require('../middleware/auth');
const cc = require('../controllers/community.controller');
const router = express.Router();
router.use(authMiddleware);
router.post('/create', cc.createCommunity);
router.get('/list', cc.getList);
router.get('/:id', cc.getDetail);
router.post('/:id/join', cc.joinCommunity);
router.post('/:id/leave', cc.leaveCommunity);
router.get('/:id/members', cc.getMembers);
module.exports = router;
