-- 任务3: 智能破冰系统
CREATE TABLE IF NOT EXISTS icebreaker_topics (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category VARCHAR(20) NOT NULL, content VARCHAR(200) NOT NULL, is_active TINYINT(1) DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS match_icebreakers (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, match_id INT UNSIGNED NOT NULL, user1_id INT UNSIGNED NOT NULL, user2_id INT UNSIGNED NOT NULL, topics JSON DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_match (match_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS icebreaker_questions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, question VARCHAR(200) NOT NULL, option_a VARCHAR(100) NOT NULL, option_b VARCHAR(100) NOT NULL, category VARCHAR(30) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 任务5: 社交游戏
CREATE TABLE IF NOT EXISTS game_rooms (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, game_type VARCHAR(20) NOT NULL, player1_id INT UNSIGNED NOT NULL, player2_id INT UNSIGNED NOT NULL, status VARCHAR(10) DEFAULT 'waiting', winner_id INT UNSIGNED DEFAULT NULL, game_data JSON DEFAULT NULL, started_at DATETIME DEFAULT NULL, ended_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS game_records (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, game_type VARCHAR(20) NOT NULL, result VARCHAR(10) NOT NULL, score INT DEFAULT 0, opponent_id INT UNSIGNED DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS guess_words (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, word VARCHAR(50) NOT NULL, hint VARCHAR(200) DEFAULT NULL, difficulty TINYINT DEFAULT 1, category VARCHAR(30) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 任务6: 社群/圈子
CREATE TABLE IF NOT EXISTS communities (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50) NOT NULL, description VARCHAR(500) DEFAULT NULL, cover_url VARCHAR(255) DEFAULT NULL, creator_id INT UNSIGNED NOT NULL, member_count INT DEFAULT 1, post_count INT DEFAULT 0, tags JSON DEFAULT NULL, join_type VARCHAR(10) DEFAULT 'free', status TINYINT(1) DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS community_members (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, community_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED NOT NULL, role VARCHAR(10) DEFAULT 'member', contribution_score INT DEFAULT 0, joined_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_community_user (community_id, user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS community_posts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, community_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED NOT NULL, content TEXT NOT NULL, images JSON DEFAULT NULL, like_count INT DEFAULT 0, comment_count INT DEFAULT 0, is_pinned TINYINT(1) DEFAULT 0, status TINYINT(1) DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS community_events (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, community_id INT UNSIGNED NOT NULL, creator_id INT UNSIGNED NOT NULL, title VARCHAR(100) NOT NULL, description TEXT, location VARCHAR(200) DEFAULT NULL, start_time DATETIME NOT NULL, max_participants INT DEFAULT NULL, participant_count INT DEFAULT 0, status TINYINT(1) DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 任务7: 聊天优化
CREATE TABLE IF NOT EXISTS chat_backgrounds (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, conversation_id INT UNSIGNED NOT NULL, background_url VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_user_conv (user_id, conversation_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS quick_replies (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, content VARCHAR(200) NOT NULL, sort_order INT DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE messages ADD COLUMN quoted_message_id INT UNSIGNED DEFAULT NULL;
ALTER TABLE messages ADD COLUMN quoted_content VARCHAR(200) DEFAULT NULL;

-- 任务9: VIP增强
CREATE TABLE IF NOT EXISTS noble_levels (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, level TINYINT NOT NULL UNIQUE, name VARCHAR(20) NOT NULL, icon_url VARCHAR(255) DEFAULT NULL, price_monthly DECIMAL(10,2) NOT NULL, privileges JSON NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS dress_up_items (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, type VARCHAR(20) NOT NULL, name VARCHAR(50) NOT NULL, preview_url VARCHAR(255) NOT NULL, resource_url VARCHAR(255) NOT NULL, price DECIMAL(10,2) DEFAULT 0, noble_level_required TINYINT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS user_dress_ups (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, item_id INT UNSIGNED NOT NULL, is_using TINYINT(1) DEFAULT 0, purchased_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_user_item (user_id, item_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE users ADD COLUMN noble_level TINYINT DEFAULT 0;
ALTER TABLE users ADD COLUMN noble_expire_time DATETIME DEFAULT NULL;

-- 种子数据
INSERT INTO noble_levels (level, name, price_monthly, privileges) VALUES (1,'骑士',30.00,'{"daily_like":50}'),(2,'子爵',68.00,'{"daily_like":-1}'),(3,'伯爵',128.00,'{"super_like_daily":3}'),(4,'侯爵',328.00,'{"super_like_daily":10}'),(5,'公爵',648.00,'{"super_like_daily":-1}') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT IGNORE INTO icebreaker_topics (category, content) VALUES ('interest','你们都喜欢{tag}！最近有什么新发现吗？'),('location','你们都在{city}，有没有推荐的餐厅？'),('fun','如果你有超能力，最想做什么？'),('value','你觉得人生中最重要的是什么？');
INSERT IGNORE INTO icebreaker_questions (question, option_a, option_b, category) VALUES ('周末更想怎么过？','宅家休息','出门浪','lifestyle'),('火锅还是刺身？','火锅','刺身','food');
INSERT IGNORE INTO guess_words (word, hint, difficulty, category) VALUES ('爱情','一种让人心动的感觉',1,'情感'),('旅行','背上行囊去看世界',1,'生活'),('火锅','冬天的最爱热辣辣',1,'美食'),('星空','夜晚抬头就能看到',2,'自然'),('彩虹','雨后天空的桥',2,'自然');
